version: '3.8'

services:
  # MySQL база данных
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: ./laravel-shop
      dockerfile: Dockerfile
    container_name: laravel_backend
    restart: always
    working_dir: /var/www
    volumes:
      - ./laravel-shop:/var/www
    depends_on:
      - mysql
    environment:
      APP_ENV: local
      APP_DEBUG: true
      APP_KEY: base64:somekey
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: laravel_db
      DB_USERNAME: laravel_user
      DB_PASSWORD: laravel_password
    ports:
      - "8000:8000"
    command: >
      sh -c "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=8000"

  frontend:
    build:
      context: ./react
      dockerfile: Dockerfile
    container_name: react_frontend
    restart: always
    working_dir: /app
    volumes:
      - ./react:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "3000"]

volumes:
  mysql_data:
